function rx = NomR_dx_zlb(in1,in2,in3)
%NomR_dx_zlb
%    RX = NomR_dx_zlb(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    29-May-2025 15:48:11

b8 = in2(8,:);
b9 = in2(9,:);
b10 = in2(10,:);
b11 = in2(11,:);
b12 = in2(12,:);
b13 = in2(13,:);
b14 = in2(14,:);
b22 = in2(22,:);
b23 = in2(23,:);
b24 = in2(24,:);
b25 = in2(25,:);
b26 = in2(26,:);
b27 = in2(27,:);
b28 = in2(28,:);
p12 = in3(12,:);
p13 = in3(13,:);
p24 = in3(24,:);
p25 = in3(25,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
t2 = b9.*x1;
t3 = b10.*x2;
t4 = b11.*x3;
t5 = b12.*x4;
t6 = b13.*x5;
t7 = b14.*x6;
t8 = b23.*x1;
t9 = b24.*x2;
t10 = b25.*x3;
t11 = b26.*x4;
t12 = b27.*x5;
t13 = b28.*x6;
t14 = p24.*p25;
t15 = -t14;
t17 = b8+t2+t3+t4+t5+t6+t7;
t18 = b22+t8+t9+t10+t11+t12+t13+x2;
t16 = exp(t15);
t19 = p12.*t17;
t20 = p13.*t18;
t21 = t19+t20+x4;
t22 = p25.*t21;
t23 = exp(t22);
t24 = t16+t23;
t25 = 1.0./t24;
rx = [t23.*t25.*(b9.*p12+b23.*p13),t23.*t25.*(b10.*p12+p13.*(b24+1.0)),t23.*t25.*(b11.*p12+b25.*p13),t23.*t25.*(b12.*p12+b26.*p13+1.0),t23.*t25.*(b13.*p12+b27.*p13),t23.*t25.*(b14.*p12+b28.*p13)];
end
